import org.junit.Test;
import sample.amqp.SampleAmqpSimpleApplication;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'hongpf' at '16-4-12 下午4:39' with Gradle 2.10
 *
 * @author hongpf, @date 16-4-12 下午4:39
 */
public class SpringBootMainTest {
    @Test public void testSomeLibraryMethod() {
        SampleAmqpSimpleApplication classUnderTest = new SampleAmqpSimpleApplication();
//      assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
